= How I installed Go on my corporate Windows laptop without administrator rights

*TLDR;* The  master trick when not having administrator rights is to use pass:q[`C:\Users\<i>username</i>\AppData\Local\Programs`], where pass:q[`<i>username</i>`] !!!

I have started by going to link:https://golang.org/[^] ;-)

There, I discovered the link:https://tour.golang.org/welcome/1[_A Tour of Go_^] which allows you to start learning the Go language without installing *anything*. Brilliant!

pass:q[<u>*_Remark:_*</u>] The _A Tour of Go_ is built on top of link:https://play.golang.org/[_Go Playground_^], a web service that runs on golang.org's servers. The service receives a Go program, compiles, links, and runs the program inside a sandbox, then returns the output. You can also use this service to share your single source file Go program in a *demo-able* mode; try link:https://play.golang.org/p/EtWwP9G5Sb[this^]! It is here that I have discovered the idea of having test sandbox giving *deterministic* output, even when using date-time ;-)

Then, on the link:https://forum.golangbridge.org/t/windows-binary-installer-without-administrator-rights/2345[Go Forum^], I directly got the confimation that using the Microsoft Windows installer package (.msi) will not work without administrtor rights :-/ But, thanks to link:http://www.mickesommar.com/[Micke Sommar^], I also got the confirmation that it is possible to install Go without administrator rights ;-)

Here is my complete procedure:

. Go to https://golang.org/dl/[^] and *DON'T* download the Microsoft Windows installer package (.msi);
. Download the latest *archive* file for Windows; I have used the link:https://storage.googleapis.com/golang/go1.6.3.windows-amd64.zip[go1.6.3.windows-amd64.zip] one;
. Then, I have unzip the content of this archive (which contains the folder `\go`) to my pass:q[`C:\Users\<i>username</i>\AppData\Local\Programs`], where pass:q[`<i>username</i>`] should be replaced by your own Windows user name. Indeed, you just need to find a place on your `C:\` drive on which you can write, and that is not cleanup periodically by your administrator!
. Finally, you can start a Command Prompt and set the following environement variables:
[listing]
C:\> set GOROOT=C:\Users\username\AppData\Local\Programs\go
C:\> set PATH=%PATH%;%GOROOT%\bin`
C:\> set GOPATH=H:\My Documents\Work\156 - 2016-06-15 - Go\work
C:\> set PATH=%PATH%;%GOPATH%\bin]

Now, you can use Go as described in the link:https://golang.org/doc/code.html[documentation^]! Have fun ;-)

